config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/9203ccec75.js" crossorigin="anonymous"></script>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit task</h1>
  <%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit class: "btn btn-primary" %>
  <%= link_to '<i class="fas fa-trash"></i> - Delete task ?'.html_safe, task_path(@task), method: :delete, data:{ confirm: "Are you sure ?"}, class: "float-right btn btn-light" %>
<% end %>
<hr>
<%= link_to '<i class="fas fa-history"></i> - Back to list'.html_safe, tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div>
    <h1>My tasks</h1>
    <ul>
      <% @tasks.each do |task| %>
        <li><% if task.completed %>
          <input type="checkbox" value="<%= task.completed %>" checked>
          <% else %>
          <input type="checkbox" value="<%= task.completed %>">
          <% end %> - <%= link_to task.title, task_path(task) %>
          ·
          <%= link_to task_path(task.id), method: :delete, data: { confirm: "Delete #{task.title}?" } do %>
          <i class="fa fa-trash-o" aria-hidden="true"></i>
         <% end %>
        </li>
      <% end %>
    </ul>
    <hr>

    <%= link_to '<i class="fas fa-plus"></i> Add new task'.html_safe, new_task_url %>

</div>

</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>New task</h1>
  <%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
<hr>
<%= link_to '<i class="fas fa-history"></i> - Back to list'.html_safe, tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <%= link_to edit_task_path(@task.id), class: "float-right btn btn-light" do %>
  <i class="fa fa-pencil"></i> Edit this task
  <% end %>

  <h2><%= @task.title %></h2>

  <p class="task-detail"><%= @task.details %></p>

  <% if @task.completed %>
  <i class="fa fa-check-square-o"></i> - This task is completed
  <% else %>
  <i class="fa fa-square-o"></i> - This task is not completed yet
  <% end %><br>

  <hr>
  <%= link_to '<i class="fas fa-history"></i> - Back to list'.html_safe, tasks_path %>
</div>